@startuml

' main program
class JobScheduler {
    - bst : BinarySearchTree
    + addJob(name, start, duration)
    + deleteJob(name)
    + viewJobs()
    + run()
}

' data structures
class BinarySearchTree {
    - root : Node
    + insertJob(jobInfo)
    + deleteJob(name)
    + jobOrder()
}

class Node {
    - name : String
    - startTime : float
    - duration : float
    - endTime : float
    - left : Node
    - right : Node
}

' relationships
JobScheduler --> BinarySearchTree
BinarySearchTree --> Node

@enduml
